// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebcfjoyqtaftakbnqafg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViY2Zqb3lxdGFmdGFrYm5xYWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODk1NTksImV4cCI6MjA2MzY2NTU1OX0.iOVL0vR4_VHkgc_X19udqb8izq01PFK2sxb8SvbTXnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);